### ISSUE TITLE
operator: KeyError: 'selfLink'

### ISSUE THREAD

**Issue by nemethf** [l7mp/l7mp#101]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 274, in execute_handler_once
    subrefs=subrefs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 374, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 119, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/l7mp.py", line 613, in create_fn
    s[o_type][get_fqn(body)] = body
  File "/src/l7mp.py", line 64, in get_fqn
    return (obj['metadata']['selfLink'])
KeyError: 'selfLink'
```

This is because selfLink has been disabled in k8s v1.20.0, kubernetes/enhancements#1164

A workaround:
 https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-742616668

The workaround won't work with k8s v1.21.

**Comment by VidarHUN** [comment]
https://www.kubernetes.dev/resources/release/#tldr
